// Derives the EP economy by brute force.
//
// Runs every badge predicate against all 1,000,001 possible rolls, counts exact
// hit frequencies, and turns those into EP values:
//
//     EP = round(100 * ROLL_SPACE / count)
//
// so a badge one roll in a million can earn is worth 100,000,100 EP and a
// coin-flip badge is worth 200. Nothing is hand-tuned; rarity *is* the price.
//
// It also scores every roll with family supersession applied, which is what the
// unreachable-badge check and the rarity distribution test are measured against.
//
// Usage: node tools/generate.mjs

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { BADGES, context, ROLL_MIN, ROLL_MAX, ROLL_SPACE } from '../defs.js';

const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'badges.gen.js');

// Card rarity: rngdle.com's own published EP cutoffs, used verbatim.
//
// Earlier builds derived these as percentiles, because this game had a smaller
// badge set and a correspondingly lower EP scale. It now implements the live
// game's full catalogue with identical EP for every badge, so a roll scores the
// same number here as there — which means the real cutoffs can be used directly
// and a given number lands in the same tier in both games.
//
// Measured against those cutoffs, our distribution comes out Mythic 0.98%,
// Anomaly 3.95%, Epic 4.92%, Common 49.34% against the live game's 1/4/5/49.1.
const CARD_TIERS = [
  ['Mythic', 164953],
  ['Anomaly', 35744],
  ['Epic', 23077],
  ['Rare', 9644],
  ['Uncommon', 5761],
  ['Common', 2098], // below this is Trash
];

const t0 = Date.now();

// --- Pass 1: exact hit counts ----------------------------------------------
const counts = new Float64Array(BADGES.length);
const tests = BADGES.map(b => b.test);

for (let n = ROLL_MIN; n <= ROLL_MAX; n++) {
  const c = context(n);
  for (let i = 0; i < tests.length; i++) if (tests[i](c)) counts[i]++;
}

const dead = BADGES.filter((b, i) => counts[i] === 0);
if (dead.length) {
  console.error('Unreachable badges (no roll earns them):', dead.map(b => b.id).join(', '));
  process.exit(1);
}

const ep = BADGES.map((b, i) => Math.round((100 * ROLL_SPACE) / counts[i]));

// --- Pass 2: total-EP distribution, with supersession -----------------------
// Family members are grouped by index so scoring is a plain array walk.
const famIndex = new Map();
BADGES.forEach((b, i) => {
  if (!b.fam) return;
  if (!famIndex.has(b.fam)) famIndex.set(b.fam, []);
  famIndex.get(b.fam).push(i);
});
const families = [...famIndex.values()];

const totals = new Float64Array(ROLL_SPACE);
for (let n = ROLL_MIN; n <= ROLL_MAX; n++) {
  const c = context(n);
  const hit = new Uint8Array(BADGES.length);
  let total = 0;
  for (let i = 0; i < tests.length; i++) {
    if (!tests[i](c)) continue;
    hit[i] = 1;
    if (!BADGES[i].fam) total += ep[i];
  }
  for (const fam of families) {
    let best = 0;
    for (const i of fam) if (hit[i] && ep[i] > best) best = ep[i];
    total += best;
  }
  totals[n - ROLL_MIN] = total;
}

const cardTiers = CARD_TIERS;

// --- Emit -------------------------------------------------------------------
const rows = BADGES.map((b, i) =>
  `  ${b.id}: [${counts[i]}, ${ep[i]}],`).join('\n');

const tierRows = cardTiers.map(([name, cut]) => `  ['${name}', ${cut}],`).join('\n');

writeFileSync(OUT, `// GENERATED by tools/generate.mjs — do not edit by hand.
//
// Exact hit counts over all ${ROLL_SPACE.toLocaleString('en-US')} possible rolls, and the EP each
// badge is therefore worth. Regenerate after changing any predicate in defs.js:
//
//     node tools/generate.mjs

/** badge id -> [number of rolls that earn it, EP it is worth]. */
export const STATS = {
${rows}
};

/** Card rarity cut points as [name, minimum total EP], best tier first. */
export const CARD_TIERS = [
${tierRows}
];
`);

const secs = ((Date.now() - t0) / 1000).toFixed(1);
console.log(`${BADGES.length} badges over ${ROLL_SPACE.toLocaleString('en-US')} rolls in ${secs}s`);
console.log(`card tiers: ${cardTiers.map(([n, v]) => `${n} >= ${v.toLocaleString('en-US')}`).join(', ')}`);
console.log(`wrote ${OUT}`);
