// Derives the EP economy by brute force.
//
// Runs every badge predicate against all 1,000,001 possible rolls, counts exact
// hit frequencies, and turns those into EP values:
//
//     EP = round(100 * ROLL_SPACE / count)
//
// so a badge one roll in a million can earn is worth 100,000,100 EP and a
// coin-flip badge is worth 200. Nothing is hand-tuned; rarity *is* the price.
//
// It then scores every roll (with family supersession applied) to find the
// percentile cuts used for card rarity, so "Epic" means a genuinely top-1%
// roll rather than a number someone picked.
//
// Usage: node tools/generate.mjs

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { BADGES, context, ROLL_MIN, ROLL_MAX, ROLL_SPACE } from '../defs.js';

const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'badges.gen.js');

// Card rarity cut points, as the share of rolls that should land at or above
// each tier. A "Mythic" card is the best 1 in 100,000 rolls.
const CARD_TIERS = [
  ['Mythic', 1 / 100000],
  ['Anomaly', 1 / 10000],
  ['Epic', 1 / 1000],
  ['Rare', 1 / 100],
  ['Uncommon', 1 / 10],
];

const t0 = Date.now();

// --- Pass 1: exact hit counts ----------------------------------------------
const counts = new Float64Array(BADGES.length);
const tests = BADGES.map(b => b.test);

for (let n = ROLL_MIN; n <= ROLL_MAX; n++) {
  const c = context(n);
  for (let i = 0; i < tests.length; i++) if (tests[i](c)) counts[i]++;
}

const dead = BADGES.filter((b, i) => counts[i] === 0);
if (dead.length) {
  console.error('Unreachable badges (no roll earns them):', dead.map(b => b.id).join(', '));
  process.exit(1);
}

const ep = BADGES.map((b, i) => Math.round((100 * ROLL_SPACE) / counts[i]));

// --- Pass 2: total-EP distribution, with supersession -----------------------
// Family members are grouped by index so scoring is a plain array walk.
const famIndex = new Map();
BADGES.forEach((b, i) => {
  if (!b.fam) return;
  if (!famIndex.has(b.fam)) famIndex.set(b.fam, []);
  famIndex.get(b.fam).push(i);
});
const families = [...famIndex.values()];

const totals = new Float64Array(ROLL_SPACE);
for (let n = ROLL_MIN; n <= ROLL_MAX; n++) {
  const c = context(n);
  const hit = new Uint8Array(BADGES.length);
  let total = 0;
  for (let i = 0; i < tests.length; i++) {
    if (!tests[i](c)) continue;
    hit[i] = 1;
    if (!BADGES[i].fam) total += ep[i];
  }
  for (const fam of families) {
    let best = 0;
    for (const i of fam) if (hit[i] && ep[i] > best) best = ep[i];
    total += best;
  }
  totals[n - ROLL_MIN] = total;
}

const sorted = Float64Array.from(totals).sort();
const quantile = share => sorted[Math.min(sorted.length - 1, Math.floor((1 - share) * sorted.length))];
const cardTiers = CARD_TIERS.map(([name, share]) => [name, quantile(share)]);

// --- Emit -------------------------------------------------------------------
const rows = BADGES.map((b, i) =>
  `  ${b.id}: [${counts[i]}, ${ep[i]}],`).join('\n');

const tierRows = cardTiers.map(([name, cut]) => `  ['${name}', ${cut}],`).join('\n');

writeFileSync(OUT, `// GENERATED by tools/generate.mjs — do not edit by hand.
//
// Exact hit counts over all ${ROLL_SPACE.toLocaleString('en-US')} possible rolls, and the EP each
// badge is therefore worth. Regenerate after changing any predicate in defs.js:
//
//     node tools/generate.mjs

export const ROLL_SPACE = ${ROLL_SPACE};

/** badge id -> [number of rolls that earn it, EP it is worth]. */
export const STATS = {
${rows}
};

/** Card rarity cut points as [name, minimum total EP], best tier first. */
export const CARD_TIERS = [
${tierRows}
];
`);

const secs = ((Date.now() - t0) / 1000).toFixed(1);
console.log(`${BADGES.length} badges over ${ROLL_SPACE.toLocaleString('en-US')} rolls in ${secs}s`);
console.log(`card tiers: ${cardTiers.map(([n, v]) => `${n} >= ${v.toLocaleString('en-US')}`).join(', ')}`);
console.log(`wrote ${OUT}`);
