/* Why each measure is on its rulebook — the mechanism, not the definition.
   Keyed by the exact measure label in rulebook.js. */
window.RULE_WHY = {

/* --- returns and profitability --- */
"ROIC": "The cleanest test of whether a business deserves the capital it keeps. It compares profit to every dollar tied up in the company, so a business that grows by pouring money into low-returning assets is exposed even while revenue rises.",
"ROIC vs cost of capital": "Growth only builds wealth when what the money earns exceeds what the money costs. Below that line, every dollar reinvested makes the company bigger and the owner poorer, which is why the spread matters more than the growth rate.",
"Return on equity": "For a lender or insurer there is no factory to measure, so the question becomes what the shareholders' own money earns. Watch it with leverage in mind — anyone can lift return on equity by borrowing more, right up until the loans go bad.",
"Operating margin": "What survives after the real costs of running the business, before financing and tax dress it up. It is the number that shows whether pricing power is holding, because competition shows up here long before it reaches the bottom line.",
"Operating margin trend": "A single year's margin tells you almost nothing; the direction over five tells you whether the moat is intact. Slowly eroding margins are the most common early sign that a business has lost its edge.",
"Operating margin across five years": "Cyclical businesses earn their best margins at the top of the cycle, which is exactly when they look cheapest. Using the five-year average as your earnings base is what stops you buying the peak.",
"Operating margin across five years, not today": "Chip margins swing from negative to spectacular inside one cycle. Judging the company on today's figure means valuing a boom as if it were permanent.",
"Segment operating margin": "A consolidated margin can hide a highly profitable core quietly funding a loss-making venture. Reading the segments separately tells you which business you are actually buying.",
"Gross margin": "How much of each sale survives the cost of producing it — the rawest measure of pricing power. What counts as good is set by the industry, but the direction over time is meaningful everywhere.",
"Gross margin trend": "In hardware, margin is defended by design wins, and design wins expire. A falling gross margin usually means the product has become a commodity, which no amount of revenue growth will fix.",
"Gross margin vs input costs": "The real test of a brand: when commodity or packaging costs rise, can the company pass them on? Holding margin through a cost spike proves pricing power in a way market share never does.",
"Gross margin excluding regulatory credits": "Carmakers can book income from selling emissions credits to rivals, which flatters the margin without a single extra car being sold. Strip it out and you see what the actual manufacturing earns.",
"EBITDA margin": "In capital-heavy businesses, depreciation of long-lived assets swamps the profit line, so EBITDA shows the cash economics of operations. Never stop there though — for these companies the capex it ignores is the whole problem.",
"Processing spread (for processors)": "A processor buys a commodity and sells a slightly different one; its profit is the gap between the two, not a margin it sets. That spread is thin, volatile, and entirely outside management's control.",

/* --- cash --- */
"Free cash flow": "Profit is an accounting opinion about the year; free cash flow is what actually reached the bank account after keeping the business running. When the two diverge for long, believe the cash.",
"Free cash flow margin": "How much of each dollar of sales converts into spendable cash. It captures working capital and capital spending that the profit line quietly leaves out.",
"Free cash flow conversion": "Profit that never turns into cash is a story. Comparing the two directly catches revenue recognised early, inventory building up, or customers who are not paying.",
"Free cash flow after maintenance capex": "Networks must spend heavily every year just to stand still. Cash flow measured before that spending flatters them; measured after, it shows what is genuinely available to owners.",
"Cash cost and free cash flow break-even": "In a commodity business you cannot control the price you sell at, so the only question that matters is the price at which you stop making money. The lower that level, the longer you survive a downturn.",
"Capex as % of revenue": "Tells you how much of the revenue has to be reinvested just to keep the business standing. A company that must spend a fifth of sales on machinery is a fundamentally different investment from one that spends a fiftieth.",
"Capex vs operating cash flow": "When capital spending starts outrunning the cash the business generates, the shortfall comes from debt or shareholders. It is the earliest signal that an investment cycle has become a financing problem.",
"Capex discipline": "This sector destroyed capital for a decade by spending most heavily when prices were highest. Discipline through the good years is the single best predictor of who is standing after the bad ones.",
"Capex cycle and refurbishment": "Hotels and casinos must be rebuilt every decade or they lose their rate. The spending is easy to defer for a few years, which makes the deferral itself a warning.",
"Capex funding plan": "A utility grows by investing, but how it pays for that matters to you: debt keeps your share of the company intact, issuing new shares dilutes it.",
"Capex and R&D commitment": "Carmakers must keep spending on the next platform whether or not this year's sales are good. It is a fixed cost dressed up as an investment decision.",

/* --- balance sheet --- */
"Debt / EBITDA": "Roughly how many years of earnings it would take to repay the debt. Past about three, decisions start getting made by the lenders rather than by management.",
"Net debt / EBITDA": "The same test, netting off cash. For utilities and telcos a higher level is normal and safe because the cash flows are contracted; for a cyclical the same number would be dangerous.",
"Net debt": "In a business whose revenue can halve without warning, the balance sheet decides who survives the trough and who is forced to sell assets at the bottom.",
"Net debt including leases": "Airlines lease most of their aircraft, and a lease is debt with a different name. Ignore it and a carrier looks far less leveraged than it is.",
"Net cash": "Cash above debt is optionality: it lets a company buy assets in a downturn, fund a bad year, or survive a shock without asking shareholders for money.",
"Interest coverage": "How many times over the profits cover the interest bill. It answers the more urgent question than total debt does — not how much is owed, but whether it can be serviced this year.",
"Debt to total assets": "For an asset-owning business this is the honest leverage measure, since the assets are the collateral. It is also what lenders look at when deciding whether to renew.",
"Net gearing": "Developers borrow against land and projects that generate nothing until they complete. High gearing in a falling property market is the classic route to a forced sale.",
"Gearing (debt to assets)": "The number that decides a REIT's fate. Too high and a fall in property values pushes it through the regulatory limit, forcing an asset sale or a discounted share issue at the worst moment.",
"Debt maturity profile": "A landlord rarely dies of empty buildings; it dies of debt coming due in a bad month. Knowing how much refinances in the next two years, and at what rate, is the whole risk.",
"Share count change": "Everything else on this page is measured per share, and the share count is the denominator. A company growing profits 5% while issuing 5% more shares has delivered you nothing.",
"Stock-based comp as % of revenue": "Paying staff in shares costs no cash, so it flatters cash flow while quietly transferring ownership away from you. Above a modest level, reported profits materially overstate what the business earns.",

/* --- growth and demand --- */
"Revenue growth, 5-year": "Direction and consistency over several years say more than any single year, which can be flattered by an acquisition or a one-off. Steady growth is also far easier to underwrite than a spike.",
"Rule of 40 (growth + FCF margin)": "A software company can buy growth by spending everything, or harvest cash by stopping investment. Adding the two together tests whether the combination is healthy rather than letting one hide the other.",
"Net revenue retention": "Whether existing customers spend more each year without any new ones being won. Above 100% the installed base grows by itself, which is the most durable growth there is.",
"Remaining performance obligation": "Revenue already contracted but not yet delivered — next year's sales, visible today. Growing slower than revenue means the future is thinner than the present.",
"Backlog (contracted, not yet booked)": "In long-cycle industries, backlog leads revenue by years. It is the earliest honest read on demand, well before anything appears in the income statement.",
"Book-to-bill or backlog": "Orders taken against work delivered. Above one the queue is growing; below one the company is working through a backlog that is not being replaced.",
"Organic volume growth (not revenue)": "Revenue growth can be entirely price. Volume tells you whether people are actually buying more of the product, and a business growing on price alone eventually runs out of room.",
"Comparable store sales, traffic vs ticket": "Strips out new openings to show whether existing shops are healthier than last year, split into more customers versus higher prices. Traffic is the honest half; ticket alone can be inflation.",
"Users and revenue per user": "A platform can grow users while earning less from each, which is not growth. The two numbers have to be read together or the story is misleading.",
"Procedure or test volume growth": "The underlying demand signal for a device maker, visible before it reaches revenue and unaffected by pricing or currency.",
"Unit deliveries and average selling price": "Volume times price is the whole automotive equation. Rising deliveries paid for with falling prices is share bought rather than demand won.",
"Volume vs price per unit": "For a fixed-cost network, a few percent of volume swings profits hugely, while price above inflation compounds. Knowing which one is driving the result tells you if it can continue.",
"Load factor and yield": "How full the planes are, and what each seat earns. Full planes at falling fares is a warning, not a triumph.",
"RevPAR or gaming volume": "Room rate and occupancy combined is the industry's demand measure. Read them separately too — full rooms at cut prices is a different business from fewer rooms at full price.",
"Rate base growth": "A regulated utility earns an allowed return on the capital the regulator lets it invest. That capital base, not sales, is what its earnings grow with.",
"Industry capacity growth on your routes": "Airline fares are set by how many seats rivals add, not by how well you run your own airline. Capacity coming in is a forecast of falling yields.",

/* --- competitive position --- */
"Market share": "Losing share while raising prices is the classic late-stage trap for a consumer brand: the numbers look fine for a couple of years, then the volume never comes back.",
"Customer concentration": "When two or three customers are most of revenue, they set your prices and can end your business with one design decision. It is the risk least visible in the financial statements.",
"Revenue concentration in the top product": "A drug company with most of its revenue in one product is a single-product company, however long the pipeline chart is. That one patent expiry is the whole investment case.",
"Patent expiry dates by product": "Pharmaceutical revenue does not decay gently; it steps down the year generics arrive, and that date is published years ahead. It is the most important knowable fact about a drug company.",
"Phase III pipeline and readout dates": "What is meant to replace the revenue that is due to expire. Late-stage trials with dates are evidence; an early pipeline is hope.",
"R&D as % of revenue": "Whether the company is spending enough to replace the products it will lose. Cutting research is the easiest way to raise this year's profit at the cost of the next decade.",
"Recurring revenue share": "Systems are often sold near cost so the consumables and service that follow can be sold for years. The recurring share tells you how much of the revenue is an annuity rather than a fresh sale each year.",
"Aftermarket share of revenue": "Engines are sold at little or no profit and earn for twenty-five years on spare parts. The aftermarket is where the money is, so its share is the quality of the whole business.",
"Aftermarket and parts revenue": "The stable half of most industrial companies. It keeps earning when new equipment sales stop, which is what makes the downturns survivable.",
"Effective fee rate": "Assets under management can rise while the fee earned on them falls, as money moves to cheaper products. Rising assets on a falling fee rate is a treadmill.",
"Net flows (not just AUM)": "Assets grow when markets rise, which tells you nothing about the manager. Flows strip the market out and show whether clients are actually choosing them.",
"Revenue mix: recurring vs performance fees": "Management fees arrive every year; performance fees arrive in good years only. Valuing the second as if it were the first is how asset managers get overpriced.",
"Licence or concession terms (gaming)": "The moat is a government licence, not the building. Its expiry date and renewal terms are the real risk, and they are public.",
"Regulatory approvals and recalls": "A device business depends on an installed base that a single recall can reset, along with the surgeon relationships that took years to build.",
"Reimbursement and rate decisions": "In healthcare the payer sets the ceiling on what can be charged. A rate decision lands directly in operating profit, with nothing management can do about it.",
"Grade and production guidance history": "Miners that chronically miss their own guidance are telling you something about the orebody or the management, and usually both.",
"Charter rates and fleet age (shipping)": "Shipping is a commodity with a cycle. Rates are set by the global fleet, and an old fleet means capital spending is coming whether or not rates cooperate.",
"Fuel cost and hedging": "The largest variable cost of an airline, and one it does not control. Hedging shifts when the pain arrives, it does not remove it.",
"Investment portfolio quality": "An insurer's float is invested, so the asset side carries risk the premiums never mention. What it holds, and for how long, decides how a credit shock hits.",
"Land bank cost vs current land prices": "Land bought decades ago at a fraction of today's prices is where a developer's margin actually comes from. Replacing it at current prices is what the next project looks like.",
"Collateral value (pawnbrokers)": "The loan book is secured against gold and watches, so its safety moves with those prices. A falling gold price shrinks both the collateral and the retail margin at once.",

/* --- credit quality --- */
"Cost-to-income ratio": "What a bank spends to earn a dollar of income — the clearest measure of whether it is well run. The gap between a good bank and an average one is worth billions in profit.",
"Non-performing loans": "The share of lending that has stopped performing. The level matters less than the direction: rising NPLs are the first visible stage of a credit cycle.",
"Allowance for loan losses / gross loans": "How much the bank has already set aside against loans going bad. Compare it to the NPL ratio: reserves far below problem loans mean provisions are still to come.",
"CET1 capital ratio": "The shareholders' own money standing between a loan loss and the depositors. It is the regulator's measure of whether the bank can absorb a bad year without help.",
"Net interest margin": "The spread between what a bank earns on loans and pays on deposits. It moves with interest rates, so its direction tells you what is about to happen to earnings.",
"Loans / deposits": "Whether the loan book is funded by depositors or by borrowing from markets. Deposit-funded is cheaper and far stickier when markets freeze.",
"Net charge-off rate": "Loans actually written off, which is the truth about underwriting after the arguments about provisioning are over. Compare it to the same stage of the last cycle.",
"30-day delinquencies": "The earliest warning in consumer lending: borrowers who have just started missing payments. It moves months ahead of charge-offs.",
"Loan growth vs provisions": "A loan book growing much faster than the money set aside against it is a business taking on risk it has not yet paid for.",
"Combined ratio (general insurance)": "Claims and expenses as a share of premiums. Below 100% the underwriting itself makes money; above it, the insurer is relying on its investments to cover bad pricing.",
"New business profit / embedded value (life)": "Life insurance profits arrive over decades, so the accounts show assumptions as much as results. New business profit is the closest thing to 'did we write good policies this year'.",
"Medical loss ratio (insurers)": "The share of premiums paid out as medical claims. A single percentage point is enormous at these revenue levels, which is why it is the number insurers manage to.",
"Occupancy and revenue per bed (hospitals)": "The two levers a hospital has: how full it is and how much each patient episode earns. Everything else is a consequence of these.",

/* --- property --- */
"Distribution per unit, five-year trend": "The payout is the reason to own a REIT, so its five-year path is the scorecard. A distribution propped up by selling assets or issuing units is not the same as one paid from rent.",
"Rental reversion": "When a lease ends and a new tenant signs, is the rent higher or lower? It is the purest signal of whether the landlord still has pricing power.",
"Occupancy and WALE": "How full the buildings are and how long the leases run. Long leases are safer but capture less upside when rents rise — which you prefer depends on the cycle.",
"Yield spread over the 10-year government bond": "What you are paid for taking property risk instead of lending to the government. When the spread narrows, you are being paid less for the same risk.",
"Price to book vs net asset value": "Property companies almost always trade below the stated value of their assets. The question is never whether there is a discount, but why this one, and what would ever close it.",
"Recurring rental income vs development profit": "Development profits arrive in lumps and can vanish for years; rent arrives monthly. The recurring share is what actually supports the dividend.",
"Unsold inventory and its age": "Finished apartments nobody has bought are capital sitting idle, and the longer they sit the more likely the price comes down.",

/* --- valuation --- */
"Price to book": "For airlines and asset-heavy cyclicals, earnings vanish at the trough and book value is what remains to anchor the price.",
"Price to book vs its own history": "For a bank, P/E swings with the credit cycle while book value is steadier, so the book multiple is the more reliable comparison — and against its own history, not another bank's.",
"Price to embedded value or book": "Insurers publish an estimate of the value of policies already written. Trading below it means the market doubts either the assumptions or the growth.",
"Payout ratio": "How much of earnings is being handed out. A high payout leaves nothing for reinvestment or a bad year, which is how dividends get cut.",
"Dividend covered by free cash flow": "Dividends are paid in cash, not earnings. A payout covered on paper but not in cash is funded by borrowing, and that only lasts so long.",
"Dividend cover and credit rating": "For a utility the dividend and the credit rating are linked: protecting the payout through a downgrade raises the cost of the debt the whole model runs on.",
"Dividend and buyback coverage at strip prices": "Test the distribution against today's commodity price, not last year's. Producers promise through-cycle payouts and then fund them with debt when prices fall.",

/* --- operations --- */
"Inventory days": "How long stock sits before it sells. Rising days mean customers slowed down before it showed up in revenue — the earliest operational warning there is.",
"Inventory days (company, not dealer)": "The company's own stock, which is not the same as vehicles sitting on dealer lots. Both rise before discounting starts, but the dealer number moves first.",
"Dealer or channel inventory": "Goods pushed into the channel are booked as sales before anyone has bought them. Channel stock rising is demand being borrowed from next year.",
"Operating ratio (rail)": "Costs as a share of revenue, the railroad industry's efficiency measure. Because the network's costs are largely fixed, small changes here move profits a great deal.",
"Subscriber churn and ARPU": "How many customers leave and what the rest pay. Rising churn is the first evidence that a price war has started.",
"New store returns / payback period": "Whether new shops earn what the existing ones do. If they earn less, expansion is destroying value while making revenue look healthy.",
"Charges on fixed-price contracts": "One-off charges that keep recurring are not one-off. In defence they usually mean the company is bidding below what the work costs.",
"Reserve life and reserve replacement": "Every barrel sold has to be replaced or the company is quietly liquidating itself. Replacement below 100% is a countdown.",
"Reserve life at current production": "How many years of digging are left at today's rate. Under about ten, the clock rather than the commodity price becomes the main risk.",
"All-in sustaining cost per unit": "Everything it costs to produce an ounce or a tonne and keep the mine running. Against the market price, it is the entire margin.",
"Allowed return on equity": "Set by the regulator, not the market. It caps how profitable a utility can be, which is the trade for its monopoly."
};
